// Rasterizing the icon set for the deck. Every icon is Hugeicons artwork
// (streamdeck/icon-set.mts, regenerated by `make icons`) drawn in one colour,
// so a tile asks for a name, a pixel size, and a tint rather than describing
// any geometry itself.
//
// Two details matter here. An SVG rasterizes at the size declared on its root
// element, not at the size it is drawn to, so the wrapper is built at the
// target size — scaling a 24px raster up to a 48px key icon is visibly soft.
// And the artwork strokes in `currentColor`, which resolves from a `color`
// attribute on that same wrapper, so tinting needs no edit of the path data.

import { Image } from '@napi-rs/canvas'

import { ICON_MARKUP, ICON_VIEWBOX, type IconName } from './icon-set.mjs'

/**
 * Rasterized icons by name, size, and tint. Every one of those comes from a
 * compiled-in layout or catalog constant, so the set is small and fixed and
 * the cache cannot grow without a code change.
 */
const cache = new Map<string, Image>()

export function iconImage(name: IconName, size: number, color: string): Image {
  // Rasterize at whole pixels: an animated key varies its icon size by a
  // fraction every frame, and caching each of those would grow without bound.
  // Drawing the whole-pixel raster at the exact size is a sub-pixel scale.
  const raster = Math.max(1, Math.round(size))
  const key = `${name}|${raster}|${color}`
  const cached = cache.get(key)
  if (cached) return cached

  const image = new Image()
  image.src = Buffer.from(
    `<svg xmlns="http://www.w3.org/2000/svg" width="${raster}" height="${raster}"` +
      ` viewBox="0 0 ${ICON_VIEWBOX} ${ICON_VIEWBOX}" fill="none" color="${color}">${ICON_MARKUP[name]}</svg>`,
  )
  cache.set(key, image)
  return image
}

/**
 * The icon for a Home Assistant weather condition, and the colour it reads
 * best in. Conditions Home Assistant adds later fall through to plain cloud
 * rather than blanking the key.
 */
export function conditionIcon(condition: string): { icon: IconName; color: string } {
  if (condition === 'clear-night') return { icon: 'moon', color: '#b0bec5' }
  if (condition.includes('sunny')) {
    return condition.startsWith('partly')
      ? { icon: 'sunCloud', color: '#ffd54f' }
      : { icon: 'sun', color: '#ffd54f' }
  }
  if (condition.startsWith('partlycloudy')) return { icon: 'sunCloud', color: '#ffd54f' }
  if (condition.includes('lightning')) return { icon: 'lightning', color: '#ffd54f' }
  if (condition.includes('hail')) return { icon: 'hail', color: '#e1f5fe' }
  if (condition.includes('snow')) return { icon: 'snow', color: '#e1f5fe' }
  if (condition.includes('rain') || condition.includes('pouring')) return { icon: 'rain', color: '#4fc3f7' }
  if (condition.includes('fog')) return { icon: 'fog', color: '#b0bec5' }
  if (condition.includes('wind')) return { icon: 'wind', color: '#b0bec5' }
  if (condition === 'exceptional') return { icon: 'alert', color: '#ff8a65' }
  return { icon: 'cloud', color: '#b0bec5' }
}

export type { IconName }
