---
- name: Install USB audio client
  ansible.builtin.include_tasks: python_package.yml
  vars:
    python_package_source: "{{ smartamp_source_dir }}/usb-audio/src/usb_audio"
    python_package_dir: "{{ smartamp_app_dir }}/usb-audio/usb_audio"
    python_package_handlers: [Restart USB audio]
    python_package_entrypoint: __main__.py

- name: Configure USB audio client
  ansible.builtin.template:
    src: usb-audio.json.j2
    dest: "{{ smartamp_config_dir }}/usb-audio.json"
    owner: root
    group: "{{ smartamp_service_user }}"
    mode: "0644"
  notify: Restart USB audio

- name: Install USB audio client service
  ansible.builtin.template:
    src: smartamp-usb-audio.service.j2
    dest: /etc/systemd/system/smartamp-usb-audio.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload systemd
    - Restart USB audio
