#!/usr/bin/env node
// Regenerates apps/controller/src/streamdeck/icon-set.mts from the Hugeicons
// free set (MIT). Run it with `make icons` after editing the ICONS map below.
//
// The icons are fetched one module at a time from a pinned version on unpkg
// rather than taken from a dependency: @hugeicons/core-free-icons unpacks to
// 125MB for 5,448 icons, and this project uses roughly thirty. The generated
// module is committed, so neither this tool nor any icon package is needed to
// build, test, or deploy the controller — only to add an icon.

import { writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'

/** The Hugeicons release the committed icon set was generated from. */
const VERSION = '4.2.3'

/**
 * The icons the control surface draws, as `name in the controller` ->
 * `Hugeicons export`. Browse the set at https://hugeicons.com/icons to find an
 * export name; it is the file name under dist/esm without the .js.
 */
const ICONS = {
  // Control surface
  mic: 'Mic01Icon',
  shuffle: 'ShuffleIcon',
  play: 'PlayIcon',
  pause: 'PauseIcon',
  next: 'ArrowRight01Icon',
  previous: 'ArrowLeft01Icon',
  volume: 'VolumeHighIcon',
  speaker: 'Speaker01Icon',
  usb: 'UsbIcon',
  note: 'MusicNote01Icon',
  playlist: 'Playlist01Icon',
  timer: 'Timer01Icon',
  // Room devices
  fan: 'Fan01Icon',
  blinds: 'BlindsIcon',
  computer: 'ComputerIcon',
  bulb: 'BulbIcon',
  thermometer: 'TemperatureIcon',
  // Weather conditions
  sun: 'Sun03Icon',
  moon: 'Moon02Icon',
  sunCloud: 'SunCloud01Icon',
  cloud: 'CloudIcon',
  rain: 'CloudMidRainIcon',
  snow: 'CloudMidSnowIcon',
  lightning: 'CloudLightningIcon',
  fog: 'CloudFogIcon',
  wind: 'FastWindIcon',
  hail: 'CloudHailstoneIcon',
  alert: 'Alert02Icon',
}

const OUTPUT = fileURLToPath(new URL('../apps/controller/src/streamdeck/icon-set.mts', import.meta.url))

/**
 * One icon's element list. A Hugeicons module is a plain array literal of
 * `[tag, attributes]` pairs assigned to a const and default-exported, so the
 * literal is lifted out and evaluated rather than parsed: the attribute keys
 * are unquoted JavaScript identifiers, not JSON.
 */
async function fetchIcon(exportName) {
  const url = `https://unpkg.com/@hugeicons/core-free-icons@${VERSION}/dist/esm/${exportName}.js`
  const response = await fetch(url)
  if (!response.ok) throw new Error(`${exportName}: ${response.status} ${response.statusText} from ${url}`)
  const source = await response.text()
  const literal = source.replace(/^\s*const\s+\w+\s*=\s*/, '').replace(/;?\s*export default\s+\w+;?\s*$/, '')
  const elements = new Function(`return ${literal}`)()
  if (!Array.isArray(elements) || elements.length === 0) throw new Error(`${exportName}: no elements`)
  return elements
}

/** React-style attribute names (strokeWidth) as SVG writes them (stroke-width). */
const attributeName = (name) => name.replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`)

/** One icon's elements as SVG markup, for embedding in a <svg> wrapper. */
function toMarkup(elements) {
  return elements
    .map(([tag, attributes]) => {
      const written = Object.entries(attributes)
        // `key` is React's list identity, meaningless in SVG.
        .filter(([name]) => name !== 'key')
        .map(([name, value]) => `${attributeName(name)}="${String(value).replace(/"/g, '&quot;')}"`)
        .join(' ')
      return `<${tag} ${written}/>`
    })
    .join('')
}

const names = Object.keys(ICONS).sort()
const markup = new Map()
for (const name of names) {
  const exportName = ICONS[name]
  markup.set(name, toMarkup(await fetchIcon(exportName)))
  process.stdout.write(`  ${name} <- ${exportName}\n`)
}

const body = names
  .map((name) => `  ${name}: '${markup.get(name).replace(/'/g, "\\'")}',`)
  .join('\n')

await writeFile(
  OUTPUT,
  `// Generated by tools/generate-icons.mjs — do not edit.
//
// Icon artwork from the Hugeicons free set ${VERSION} (MIT licence),
// https://hugeicons.com. Each entry is the inner markup of a 24x24 icon,
// stroked in \`currentColor\` so streamdeck/icons.mts can colour it per state.
//
// Run \`make icons\` to add an icon or move to a newer Hugeicons release.

/** Every icon is authored on this square, which is what scales it to a key. */
export const ICON_VIEWBOX = 24

export const ICON_MARKUP = {
${body}
} as const

/** The icons a tile or screen may draw, checked at compile time. */
export type IconName = keyof typeof ICON_MARKUP
`,
  'utf8',
)

process.stdout.write(`\n${names.length} icons -> ${OUTPUT}\n`)
