#!/usr/bin/env node
// Regenerates apps/controller/src/streamdeck/icon-set.mts from the Hugeicons
// free set (MIT). Run it with `make icons` after editing the ICONS map below.
//
// @hugeicons/core-free-icons is a devDependency of the workspace root, never of
// the controller: it unpacks to 83MB for 5,448 icons and this project draws
// roughly thirty. It publishes one ESM module per icon, so only the icons named
// below are ever imported. The generated module is committed, so neither this
// tool nor any icon package is needed to build, test, or deploy the controller —
// only to add an icon.

import {readFile, writeFile} from 'node:fs/promises'
import {fileURLToPath} from 'node:url'

/**
 * The installed Hugeicons release, stamped into the generated header so it
 * cannot drift from what the icons were actually taken from. The package is a
 * root devDependency; pnpm-lock.yaml is what pins it.
 */
const PACKAGE = new URL('../node_modules/@hugeicons/core-free-icons/', import.meta.url)
const VERSION = await readFile(new URL('package.json', PACKAGE), 'utf8')
    .then((raw) => JSON.parse(raw).version)
    .catch(() => {
        throw new Error('@hugeicons/core-free-icons is not installed. Run `pnpm install` first.')
    })

/**
 * The icons the control surface draws, as `name in the controller` ->
 * `Hugeicons export`. Browse the set at https://hugeicons.com/icons to find an
 * export name; it is the file name under dist/esm without the .js.
 */
const ICONS = {
    // Control surface
    mic: 'Mic01Icon',
    micOff: 'MicOff01Icon',
    shuffle: 'ShuffleIcon',
    repeat: 'RepeatIcon',
    repeatOne: 'RepeatOne01Icon',
    play: 'PlayIcon',
    pause: 'PauseIcon',
    next: 'ArrowRight01Icon',
    previous: 'ArrowLeft01Icon',
    volume: 'VolumeHighIcon',
    volumeMute: 'VolumeMute02Icon',
    voice: 'AiVoiceIcon',
    usb: 'UsbIcon',
    note: 'MusicNote01Icon',
    playlist: 'Playlist01Icon',
    timer: 'Timer01Icon',
    power: 'ShutDownIcon',
    // System health status
    wifi: 'Wifi01Icon',
    home: 'Home01Icon',
    // Room devices
    fan: 'Fan01Icon',
    blinds: 'BlindsIcon',
    computer: 'ComputerIcon',
    bulb: 'BulbIcon',
    thermometer: 'TemperatureIcon',
    // Weather conditions
    sun: 'Sun03Icon',
    moon: 'Moon02Icon',
    sunCloud: 'SunCloud01Icon',
    cloud: 'CloudIcon',
    rain: 'CloudMidRainIcon',
    snow: 'CloudMidSnowIcon',
    lightning: 'CloudLightningIcon',
    fog: 'CloudFogIcon',
    wind: 'FastWindIcon',
    hail: 'CloudHailstoneIcon',
    alert: 'Alert02Icon',
}

const OUTPUT = fileURLToPath(new URL('../apps/controller/src/streamdeck/icon-set.mts', import.meta.url))

/**
 * One icon's element list: a Hugeicons module default-exports an array of
 * `[tag, attributes]` pairs. Each is imported by its own path so adding an icon
 * costs one module rather than loading all 5,448.
 */
async function loadIcon(exportName) {
    const module = await import(new URL(`dist/esm/${exportName}.js`, PACKAGE)).catch(() => {
        throw new Error(`${exportName}: no such icon in @hugeicons/core-free-icons@${VERSION}`)
    })
    const elements = module.default
    if (!Array.isArray(elements) || elements.length === 0) throw new Error(`${exportName}: no elements`)
    return elements
}

/** React-style attribute names (strokeWidth) as SVG writes them (stroke-width). */
const attributeName = (name) => name.replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`)

/** One icon's elements as SVG markup, for embedding in a <svg> wrapper. */
function toMarkup(elements) {
    return elements
        .map(([tag, attributes]) => {
            const written = Object.entries(attributes)
                // `key` is React's list identity, meaningless in SVG.
                .filter(([name]) => name !== 'key')
                .map(([name, value]) => `${attributeName(name)}="${String(value).replace(/"/g, '&quot;')}"`)
                .join(' ')
            return `<${tag} ${written}/>`
        })
        .join('')
}

const names = Object.keys(ICONS).sort()
const markup = new Map()
for (const name of names) {
    const exportName = ICONS[name]
    markup.set(name, toMarkup(await loadIcon(exportName)))
    process.stdout.write(`  ${name} <- ${exportName}\n`)
}

const body = names
    .map((name) => `  ${name}: '${markup.get(name).replace(/'/g, "\\'")}',`)
    .join('\n')

await writeFile(
    OUTPUT,
    `// Generated by tools/generate-icons.mjs — do not edit.
//
// Icon artwork from the Hugeicons free set ${VERSION} (MIT licence),
// https://hugeicons.com. Each entry is the inner markup of a 24x24 icon,
// stroked in \`currentColor\` so streamdeck/icons.mts can colour it per state.
//
// Run \`make icons\` to add an icon or move to a newer Hugeicons release.

/** Every icon is authored on this square, which is what scales it to a key. */
export const ICON_VIEWBOX = 24

export const ICON_MARKUP = {
${body}
} as const

/** The icons a tile or screen may draw, checked at compile time. */
export type IconName = keyof typeof ICON_MARKUP
`,
    'utf8',
)

process.stdout.write(`\n${names.length} icons -> ${OUTPUT}\n`)
